msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2022-10-23 10:58-0500\n"
"PO-Revision-Date: 2022-10-23 16:21\n"
"Last-Translator: \n"
"Language-Team: Chinese Traditional, Macau\n"
"Language: zh_MO\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: duplicity\n"
"X-Crowdin-Project-ID: 539508\n"
"X-Crowdin-Language: zh-MO\n"
"X-Crowdin-File: /main/po/duplicity.pot\n"
"X-Crowdin-File-ID: 6\n"

#: ../bin/duplicity:107
msgid "INT intercepted...exiting."
msgstr ""

#: ../bin/duplicity:115
#, python-format
msgid "GPG error detail: %s"
msgstr ""

#: ../bin/duplicity:125
#, python-format
msgid "User error detail: %s"
msgstr ""

#: ../bin/duplicity:135
#, python-format
msgid "Backend error detail: %s"
msgstr ""

#: ../bin/rdiffdir:64 ../duplicity/commandline.py:240
#, python-format
msgid "Error opening file %s"
msgstr ""

#: ../bin/rdiffdir:131
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr ""

#: ../duplicity/tempdir.py:160
#, python-format
msgid "Using temporary directory %s"
msgstr ""

#: ../duplicity/tempdir.py:204
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:226
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:258
#, python-format
msgid "Forgetting temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:261
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""

#: ../duplicity/tempdir.py:280
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:283
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr ""

#: ../duplicity/tempdir.py:288
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""

#: ../duplicity/backend.py:102
#, python-format
msgid "Import of %s %s"
msgstr ""

#: ../duplicity/backend.py:211
#, python-format
msgid "Could not initialize backend: %s"
msgstr ""

#: ../duplicity/backend.py:403
#, python-format
msgid "Backtrace of previous error: %s"
msgstr ""

#: ../duplicity/backend.py:419
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr ""

#: ../duplicity/backend.py:423
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backend.py:517
#, python-format
msgid "Reading results of '%s'"
msgstr ""

#: ../duplicity/backend.py:543
#, python-format
msgid "Writing %s"
msgstr ""

#: ../duplicity/backend.py:584
#, python-format
msgid "File %s not found locally after get from backend"
msgstr ""

#: ../duplicity/gpg_error_codes.py:9
msgid "Success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:10
msgid "General error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:11
msgid "Unknown packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:12
msgid "Unknown version in packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:13
msgid "Invalid public key algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:14
msgid "Invalid digest algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:15
msgid "Bad public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:16
msgid "Bad secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:17
msgid "Bad signature"
msgstr ""

#: ../duplicity/gpg_error_codes.py:18
msgid "No public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:19
msgid "Checksum error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:20
msgid "Bad passphrase"
msgstr ""

#: ../duplicity/gpg_error_codes.py:21
msgid "Invalid cipher algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:22
msgid "Cannot open keyring"
msgstr ""

#: ../duplicity/gpg_error_codes.py:23
msgid "Invalid packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:24
msgid "Invalid armor"
msgstr ""

#: ../duplicity/gpg_error_codes.py:25
msgid "No user ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:26
msgid "No secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:27
msgid "Wrong secret key used"
msgstr ""

#: ../duplicity/gpg_error_codes.py:28
msgid "Bad session key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:29
msgid "Unknown compression algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:30
msgid "Number is not prime"
msgstr ""

#: ../duplicity/gpg_error_codes.py:31
msgid "Invalid encoding method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:32
msgid "Invalid encryption scheme"
msgstr ""

#: ../duplicity/gpg_error_codes.py:33
msgid "Invalid signature scheme"
msgstr ""

#: ../duplicity/gpg_error_codes.py:34
msgid "Invalid attribute"
msgstr ""

#: ../duplicity/gpg_error_codes.py:35
msgid "No value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:36
msgid "Not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:37
msgid "Value not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:38
msgid "Syntax error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:39
msgid "Bad MPI value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:40
msgid "Invalid passphrase"
msgstr ""

#: ../duplicity/gpg_error_codes.py:41
msgid "Invalid signature class"
msgstr ""

#: ../duplicity/gpg_error_codes.py:42
msgid "Resources exhausted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:43
msgid "Invalid keyring"
msgstr ""

#: ../duplicity/gpg_error_codes.py:44
msgid "Trust DB error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:45
msgid "Bad certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:46
msgid "Invalid user ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:47
msgid "Unexpected error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:48
msgid "Time conflict"
msgstr ""

#: ../duplicity/gpg_error_codes.py:49
msgid "Keyserver error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:50
msgid "Wrong public key algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:51
msgid "Tribute to D. A."
msgstr ""

#: ../duplicity/gpg_error_codes.py:52
msgid "Weak encryption key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:53
msgid "Invalid key length"
msgstr ""

#: ../duplicity/gpg_error_codes.py:54
msgid "Invalid argument"
msgstr ""

#: ../duplicity/gpg_error_codes.py:55
msgid "Syntax error in URI"
msgstr ""

#: ../duplicity/gpg_error_codes.py:56
msgid "Invalid URI"
msgstr ""

#: ../duplicity/gpg_error_codes.py:57
msgid "Network error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:58
msgid "Unknown host"
msgstr ""

#: ../duplicity/gpg_error_codes.py:59
msgid "Selftest failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:60
msgid "Data not encrypted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:61
msgid "Data not processed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:62
msgid "Unusable public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:63
msgid "Unusable secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:64
msgid "Invalid value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:65
msgid "Bad certificate chain"
msgstr ""

#: ../duplicity/gpg_error_codes.py:66
msgid "Missing certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:67
msgid "No data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:68
msgid "Bug"
msgstr ""

#: ../duplicity/gpg_error_codes.py:69
msgid "Not supported"
msgstr ""

#: ../duplicity/gpg_error_codes.py:70
msgid "Invalid operation code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:71
msgid "Timeout"
msgstr ""

#: ../duplicity/gpg_error_codes.py:72
msgid "Internal error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:73
msgid "EOF (gcrypt)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:74
msgid "Invalid object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:75
msgid "Provided object is too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:76
msgid "Provided object is too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:77
msgid "Missing item in object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:78
msgid "Not implemented"
msgstr ""

#: ../duplicity/gpg_error_codes.py:79
msgid "Conflicting use"
msgstr ""

#: ../duplicity/gpg_error_codes.py:80
msgid "Invalid cipher mode"
msgstr ""

#: ../duplicity/gpg_error_codes.py:81
msgid "Invalid flag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:82
msgid "Invalid handle"
msgstr ""

#: ../duplicity/gpg_error_codes.py:83
msgid "Result truncated"
msgstr ""

#: ../duplicity/gpg_error_codes.py:84
msgid "Incomplete line"
msgstr ""

#: ../duplicity/gpg_error_codes.py:85
msgid "Invalid response"
msgstr ""

#: ../duplicity/gpg_error_codes.py:86
msgid "No agent running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:87
msgid "Agent error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:88
msgid "Invalid data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:89
msgid "Unspecific Assuan server fault"
msgstr ""

#: ../duplicity/gpg_error_codes.py:90
msgid "General Assuan error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:91
msgid "Invalid session key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:92
msgid "Invalid S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:93
msgid "Unsupported algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:94
msgid "No pinentry"
msgstr ""

#: ../duplicity/gpg_error_codes.py:95
msgid "pinentry error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:96
msgid "Bad PIN"
msgstr ""

#: ../duplicity/gpg_error_codes.py:97
msgid "Invalid name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:98
msgid "Bad data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:99
msgid "Invalid parameter"
msgstr ""

#: ../duplicity/gpg_error_codes.py:100
msgid "Wrong card"
msgstr ""

#: ../duplicity/gpg_error_codes.py:101
msgid "No dirmngr"
msgstr ""

#: ../duplicity/gpg_error_codes.py:102
msgid "dirmngr error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:103
msgid "Certificate revoked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:104
msgid "No CRL known"
msgstr ""

#: ../duplicity/gpg_error_codes.py:105
msgid "CRL too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:106
msgid "Line too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:107
msgid "Not trusted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:108
msgid "Operation cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:109
msgid "Bad CA certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:110
msgid "Certificate expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:111
msgid "Certificate too young"
msgstr ""

#: ../duplicity/gpg_error_codes.py:112
msgid "Unsupported certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:113
msgid "Unknown S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:114
msgid "Unsupported protection"
msgstr ""

#: ../duplicity/gpg_error_codes.py:115
msgid "Corrupted protection"
msgstr ""

#: ../duplicity/gpg_error_codes.py:116
msgid "Ambiguous name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:117
msgid "Card error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:118
msgid "Card reset required"
msgstr ""

#: ../duplicity/gpg_error_codes.py:119
msgid "Card removed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:120
msgid "Invalid card"
msgstr ""

#: ../duplicity/gpg_error_codes.py:121
msgid "Card not present"
msgstr ""

#: ../duplicity/gpg_error_codes.py:122
msgid "Not confirmed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:123
msgid "Configuration error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:124
msgid "No policy match"
msgstr ""

#: ../duplicity/gpg_error_codes.py:125
msgid "Invalid index"
msgstr ""

#: ../duplicity/gpg_error_codes.py:126
msgid "Invalid ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:127
msgid "No SmartCard daemon"
msgstr ""

#: ../duplicity/gpg_error_codes.py:128
msgid "SmartCard daemon error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:129
msgid "Unsupported protocol"
msgstr ""

#: ../duplicity/gpg_error_codes.py:130
msgid "Bad PIN method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:131
msgid "Card not initialized"
msgstr ""

#: ../duplicity/gpg_error_codes.py:132
msgid "Unsupported operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:133
msgid "Wrong key usage"
msgstr ""

#: ../duplicity/gpg_error_codes.py:134
msgid "Nothing found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:135
msgid "Wrong blob type"
msgstr ""

#: ../duplicity/gpg_error_codes.py:136
msgid "Missing value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:137
msgid "Hardware problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:138
msgid "PIN blocked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:139
msgid "Conditions of use not satisfied"
msgstr ""

#: ../duplicity/gpg_error_codes.py:140
msgid "PINs are not synced"
msgstr ""

#: ../duplicity/gpg_error_codes.py:141
msgid "Invalid CRL"
msgstr ""

#: ../duplicity/gpg_error_codes.py:142
msgid "BER error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:143
msgid "Invalid BER"
msgstr ""

#: ../duplicity/gpg_error_codes.py:144
msgid "Element not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:145
msgid "Identifier not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:146
msgid "Invalid tag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:147
msgid "Invalid length"
msgstr ""

#: ../duplicity/gpg_error_codes.py:148
msgid "Invalid key info"
msgstr ""

#: ../duplicity/gpg_error_codes.py:149
msgid "Unexpected tag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:150
msgid "Not DER encoded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:151
msgid "No CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:152
msgid "Invalid CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:153
msgid "Unknown CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:154
msgid "Unsupported CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:155
msgid "Unsupported encoding"
msgstr ""

#: ../duplicity/gpg_error_codes.py:156
msgid "Unsupported CMS version"
msgstr ""

#: ../duplicity/gpg_error_codes.py:157
msgid "Unknown algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:158
msgid "Invalid crypto engine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:159
msgid "Public key not trusted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:160
msgid "Decryption failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:161
msgid "Key expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:162
msgid "Signature expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:163
msgid "Encoding problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:164
msgid "Invalid state"
msgstr ""

#: ../duplicity/gpg_error_codes.py:165
msgid "Duplicated value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:166
msgid "Missing action"
msgstr ""

#: ../duplicity/gpg_error_codes.py:167
msgid "ASN.1 module not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:168
msgid "Invalid OID string"
msgstr ""

#: ../duplicity/gpg_error_codes.py:169
msgid "Invalid time"
msgstr ""

#: ../duplicity/gpg_error_codes.py:170
msgid "Invalid CRL object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:171
msgid "Unsupported CRL version"
msgstr ""

#: ../duplicity/gpg_error_codes.py:172
msgid "Invalid certificate object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:173
msgid "Unknown name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:174
msgid "A locale function failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:175
msgid "Not locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:176
msgid "Protocol violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:177
msgid "Invalid MAC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:178
msgid "Invalid request"
msgstr ""

#: ../duplicity/gpg_error_codes.py:179
msgid "Unknown extension"
msgstr ""

#: ../duplicity/gpg_error_codes.py:180
msgid "Unknown critical extension"
msgstr ""

#: ../duplicity/gpg_error_codes.py:181
msgid "Locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:182
msgid "Unknown option"
msgstr ""

#: ../duplicity/gpg_error_codes.py:183
msgid "Unknown command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:184
msgid "Not operational"
msgstr ""

#: ../duplicity/gpg_error_codes.py:185
msgid "No passphrase given"
msgstr ""

#: ../duplicity/gpg_error_codes.py:186
msgid "No PIN given"
msgstr ""

#: ../duplicity/gpg_error_codes.py:187
msgid "Not enabled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:188
msgid "No crypto engine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:189
msgid "Missing key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:190
msgid "Too many objects"
msgstr ""

#: ../duplicity/gpg_error_codes.py:191
msgid "Limit reached"
msgstr ""

#: ../duplicity/gpg_error_codes.py:192
msgid "Not initialized"
msgstr ""

#: ../duplicity/gpg_error_codes.py:193
msgid "Missing issuer certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:194
msgid "No keyserver available"
msgstr ""

#: ../duplicity/gpg_error_codes.py:195
msgid "Invalid elliptic curve"
msgstr ""

#: ../duplicity/gpg_error_codes.py:196
msgid "Unknown elliptic curve"
msgstr ""

#: ../duplicity/gpg_error_codes.py:197
msgid "Duplicated key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:198
msgid "Ambiguous result"
msgstr ""

#: ../duplicity/gpg_error_codes.py:199
msgid "No crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:200
msgid "Wrong crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:201
msgid "Bad crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:202
msgid "Conflict in the crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:203
msgid "Broken public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:204
msgid "Broken secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:205
msgid "Invalid MAC algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:206
msgid "Operation fully cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:207
msgid "Operation not yet finished"
msgstr ""

#: ../duplicity/gpg_error_codes.py:208
msgid "Buffer too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:209
msgid "Invalid length specifier in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:210
msgid "String too long in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:211
msgid "Unmatched parentheses in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:212
msgid "S-expression not canonical"
msgstr ""

#: ../duplicity/gpg_error_codes.py:213
msgid "Bad character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:214
msgid "Bad quotation in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:215
msgid "Zero prefix in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:216
msgid "Nested display hints in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:217
msgid "Unmatched display hints"
msgstr ""

#: ../duplicity/gpg_error_codes.py:218
msgid "Unexpected reserved punctuation in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:219
msgid "Bad hexadecimal character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:220
msgid "Odd hexadecimal numbers in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:221
msgid "Bad octal character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:222
msgid "All subkeys are expired or revoked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:223
msgid "Database is corrupted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:224
msgid "Server indicated a failure"
msgstr ""

#: ../duplicity/gpg_error_codes.py:225
msgid "No name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:226
msgid "No key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:227
msgid "Legacy key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:228
msgid "Request too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:229
msgid "Request too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:230
msgid "Object is in termination state"
msgstr ""

#: ../duplicity/gpg_error_codes.py:231
msgid "No certificate chain"
msgstr ""

#: ../duplicity/gpg_error_codes.py:232
msgid "Certificate is too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:233
msgid "Invalid record"
msgstr ""

#: ../duplicity/gpg_error_codes.py:234
msgid "The MAC does not verify"
msgstr ""

#: ../duplicity/gpg_error_codes.py:235
msgid "Unexpected message"
msgstr ""

#: ../duplicity/gpg_error_codes.py:236
msgid "Compression or decompression failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:237
msgid "A counter would wrap"
msgstr ""

#: ../duplicity/gpg_error_codes.py:238
msgid "Fatal alert message received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:239
msgid "No cipher algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:240
msgid "Missing client certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:241
msgid "Close notification received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:242
msgid "Ticket expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:243
msgid "Bad ticket"
msgstr ""

#: ../duplicity/gpg_error_codes.py:244
msgid "Unknown identity"
msgstr ""

#: ../duplicity/gpg_error_codes.py:245
msgid "Bad certificate message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:246
msgid "Bad certificate request message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:247
msgid "Bad certificate verify message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:248
msgid "Bad change cipher message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:249
msgid "Bad client hello message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:250
msgid "Bad server hello message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:251
msgid "Bad server hello done message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:252
msgid "Bad finished message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:253
msgid "Bad server key exchange message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:254
msgid "Bad client key exchange message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:255
msgid "Bogus string"
msgstr ""

#: ../duplicity/gpg_error_codes.py:256
msgid "Forbidden"
msgstr ""

#: ../duplicity/gpg_error_codes.py:257
msgid "Key disabled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:258
msgid "Not possible with a card based key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:259
msgid "Invalid lock object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:260
msgid "True"
msgstr ""

#: ../duplicity/gpg_error_codes.py:261
msgid "False"
msgstr ""

#: ../duplicity/gpg_error_codes.py:262
msgid "General IPC error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:263
msgid "IPC accept call failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:264
msgid "IPC connect call failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:265
msgid "Invalid IPC response"
msgstr ""

#: ../duplicity/gpg_error_codes.py:266
msgid "Invalid value passed to IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:267
msgid "Incomplete line passed to IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:268
msgid "Line passed to IPC too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:269
msgid "Nested IPC commands"
msgstr ""

#: ../duplicity/gpg_error_codes.py:270
msgid "No data callback in IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:271
msgid "No inquire callback in IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:272
msgid "Not an IPC server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:273
msgid "Not an IPC client"
msgstr ""

#: ../duplicity/gpg_error_codes.py:274
msgid "Problem starting IPC server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:275
msgid "IPC read error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:276
msgid "IPC write error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:277
msgid "Too much data for IPC layer"
msgstr ""

#: ../duplicity/gpg_error_codes.py:278
msgid "Unexpected IPC command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:279
msgid "Unknown IPC command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:280
msgid "IPC syntax error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:281
msgid "IPC call has been cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:282
msgid "No input source for IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:283
msgid "No output source for IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:284
msgid "IPC parameter error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:285
msgid "Unknown IPC inquire"
msgstr ""

#: ../duplicity/gpg_error_codes.py:286
msgid "Crypto engine too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:287
msgid "Screen or window too small"
msgstr ""

#: ../duplicity/gpg_error_codes.py:288
msgid "Screen or window too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:289
msgid "Required environment variable not set"
msgstr ""

#: ../duplicity/gpg_error_codes.py:290
msgid "User ID already exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:291
msgid "Name already exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:292
msgid "Duplicated name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:293
msgid "Object is too young"
msgstr ""

#: ../duplicity/gpg_error_codes.py:294
msgid "Object is too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:295
msgid "Unknown flag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:296
msgid "Invalid execution order"
msgstr ""

#: ../duplicity/gpg_error_codes.py:297
msgid "Already fetched"
msgstr ""

#: ../duplicity/gpg_error_codes.py:298
msgid "Try again later"
msgstr ""

#: ../duplicity/gpg_error_codes.py:299
msgid "Wrong name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:300
msgid "Not authenticated"
msgstr ""

#: ../duplicity/gpg_error_codes.py:301
msgid "Bad authentication"
msgstr ""

#: ../duplicity/gpg_error_codes.py:302
msgid "No Keybox daemon running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:303
msgid "Keybox daemon error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:304
msgid "Service is not running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:305
msgid "Service error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:306
msgid "System bug detected"
msgstr ""

#: ../duplicity/gpg_error_codes.py:307
msgid "Unknown DNS error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:308
msgid "Invalid DNS section"
msgstr ""

#: ../duplicity/gpg_error_codes.py:309
msgid "Invalid textual address form"
msgstr ""

#: ../duplicity/gpg_error_codes.py:310
msgid "Missing DNS query packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:311
msgid "Missing DNS answer packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:312
msgid "Connection closed in DNS"
msgstr ""

#: ../duplicity/gpg_error_codes.py:313
msgid "Verification failed in DNS"
msgstr ""

#: ../duplicity/gpg_error_codes.py:314
msgid "DNS Timeout"
msgstr ""

#: ../duplicity/gpg_error_codes.py:315
msgid "General LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:316
msgid "General LDAP attribute error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:317
msgid "General LDAP name error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:318
msgid "General LDAP security error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:319
msgid "General LDAP service error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:320
msgid "General LDAP update error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:321
msgid "Experimental LDAP error code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:322
msgid "Private LDAP error code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:323
msgid "Other general LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:324
msgid "LDAP connecting failed (X)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:325
msgid "LDAP referral limit exceeded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:326
msgid "LDAP client loop"
msgstr ""

#: ../duplicity/gpg_error_codes.py:327
msgid "No LDAP results returned"
msgstr ""

#: ../duplicity/gpg_error_codes.py:328
msgid "LDAP control not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:329
msgid "Not supported by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:330
msgid "LDAP connect error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:331
msgid "Out of memory in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:332
msgid "Bad parameter to an LDAP routine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:333
msgid "User cancelled LDAP operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:334
msgid "Bad LDAP search filter"
msgstr ""

#: ../duplicity/gpg_error_codes.py:335
msgid "Unknown LDAP authentication method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:336
msgid "Timeout in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:337
msgid "LDAP decoding error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:338
msgid "LDAP encoding error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:339
msgid "LDAP local error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:340
msgid "Cannot contact LDAP server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:341
msgid "LDAP success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:342
msgid "LDAP operations error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:343
msgid "LDAP protocol error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:344
msgid "Time limit exceeded in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:345
msgid "Size limit exceeded in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:346
msgid "LDAP compare false"
msgstr ""

#: ../duplicity/gpg_error_codes.py:347
msgid "LDAP compare true"
msgstr ""

#: ../duplicity/gpg_error_codes.py:348
msgid "LDAP authentication method not supported"
msgstr ""

#: ../duplicity/gpg_error_codes.py:349
msgid "Strong(er) LDAP authentication required"
msgstr ""

#: ../duplicity/gpg_error_codes.py:350
msgid "Partial LDAP results+referral received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:351
msgid "LDAP referral"
msgstr ""

#: ../duplicity/gpg_error_codes.py:352
msgid "Administrative LDAP limit exceeded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:353
msgid "Critical LDAP extension is unavailable"
msgstr ""

#: ../duplicity/gpg_error_codes.py:354
msgid "Confidentiality required by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:355
msgid "LDAP SASL bind in progress"
msgstr ""

#: ../duplicity/gpg_error_codes.py:356
msgid "No such LDAP attribute"
msgstr ""

#: ../duplicity/gpg_error_codes.py:357
msgid "Undefined LDAP attribute type"
msgstr ""

#: ../duplicity/gpg_error_codes.py:358
msgid "Inappropriate matching in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:359
msgid "Constraint violation in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:360
msgid "LDAP type or value exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:361
msgid "Invalid syntax in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:362
msgid "No such LDAP object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:363
msgid "LDAP alias problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:364
msgid "Invalid DN syntax in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:365
msgid "LDAP entry is a leaf"
msgstr ""

#: ../duplicity/gpg_error_codes.py:366
msgid "LDAP alias dereferencing problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:367
msgid "LDAP proxy authorization failure (X)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:368
msgid "Inappropriate LDAP authentication"
msgstr ""

#: ../duplicity/gpg_error_codes.py:369
msgid "Invalid LDAP credentials"
msgstr ""

#: ../duplicity/gpg_error_codes.py:370
msgid "Insufficient access for LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:371
msgid "LDAP server is busy"
msgstr ""

#: ../duplicity/gpg_error_codes.py:372
msgid "LDAP server is unavailable"
msgstr ""

#: ../duplicity/gpg_error_codes.py:373
msgid "LDAP server is unwilling to perform"
msgstr ""

#: ../duplicity/gpg_error_codes.py:374
msgid "Loop detected by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:375
msgid "LDAP naming violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:376
msgid "LDAP object class violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:377
msgid "LDAP operation not allowed on non-leaf"
msgstr ""

#: ../duplicity/gpg_error_codes.py:378
msgid "LDAP operation not allowed on RDN"
msgstr ""

#: ../duplicity/gpg_error_codes.py:379
msgid "Already exists (LDAP)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:380
msgid "Cannot modify LDAP object class"
msgstr ""

#: ../duplicity/gpg_error_codes.py:381
msgid "LDAP results too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:382
msgid "LDAP operation affects multiple DSAs"
msgstr ""

#: ../duplicity/gpg_error_codes.py:383
msgid "Virtual LDAP list view error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:384
msgid "Other LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:385
msgid "Resources exhausted in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:386
msgid "Security violation in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:387
msgid "Invalid data in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:388
msgid "Unsupported scheme in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:389
msgid "Reload required in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:390
msgid "LDAP cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:391
msgid "No LDAP operation to cancel"
msgstr ""

#: ../duplicity/gpg_error_codes.py:392
msgid "Too late to cancel LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:393
msgid "Cannot cancel LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:394
msgid "LDAP assertion failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:395
msgid "Proxied authorization denied by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:396
msgid "SQL success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:397
msgid "SQL error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:398
msgid "Internal logic error in SQL library"
msgstr ""

#: ../duplicity/gpg_error_codes.py:399
msgid "Access permission denied (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:400
msgid "SQL abort was requested"
msgstr ""

#: ../duplicity/gpg_error_codes.py:401
msgid "SQL database file is locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:402
msgid "An SQL table in the database is locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:403
msgid "SQL library ran out of core"
msgstr ""

#: ../duplicity/gpg_error_codes.py:404
msgid "Attempt to write a readonly SQL database"
msgstr ""

#: ../duplicity/gpg_error_codes.py:405
msgid "SQL operation terminated by interrupt"
msgstr ""

#: ../duplicity/gpg_error_codes.py:406
msgid "I/O error during SQL operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:407
msgid "SQL database disk image is malformed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:408
msgid "Unknown opcode in SQL file control"
msgstr ""

#: ../duplicity/gpg_error_codes.py:409
msgid "Insertion failed because SQL database is full"
msgstr ""

#: ../duplicity/gpg_error_codes.py:410
msgid "Unable to open the SQL database file"
msgstr ""

#: ../duplicity/gpg_error_codes.py:411
msgid "SQL database lock protocol error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:412
msgid "(internal SQL code: empty)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:413
msgid "SQL database schema changed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:414
msgid "String or blob exceeds size limit (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:415
msgid "SQL abort due to constraint violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:416
msgid "Data type mismatch (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:417
msgid "SQL library used incorrectly"
msgstr ""

#: ../duplicity/gpg_error_codes.py:418
msgid "SQL library uses unsupported OS features"
msgstr ""

#: ../duplicity/gpg_error_codes.py:419
msgid "Authorization denied (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:420
msgid "(unused SQL code: format)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:421
msgid "SQL bind parameter out of range"
msgstr ""

#: ../duplicity/gpg_error_codes.py:422
msgid "File opened that is not an SQL database file"
msgstr ""

#: ../duplicity/gpg_error_codes.py:423
msgid "Notifications from SQL logger"
msgstr ""

#: ../duplicity/gpg_error_codes.py:424
msgid "Warnings from SQL logger"
msgstr ""

#: ../duplicity/gpg_error_codes.py:425
msgid "SQL has another row ready"
msgstr ""

#: ../duplicity/gpg_error_codes.py:426
msgid "SQL has finished executing"
msgstr ""

#: ../duplicity/gpg_error_codes.py:427
msgid "System error w/o errno"
msgstr ""

#: ../duplicity/gpg_error_codes.py:428
msgid "Unknown system error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:429
msgid "End of file"
msgstr ""

#: ../duplicity/manifest.py:99
#, python-format
msgid "Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""

#: ../duplicity/manifest.py:106
#, python-format
msgid "Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr ""

#: ../duplicity/manifest.py:116
msgid "Aborting because you may have accidentally tried to backup two different data sets to the same remote location, or using the same archive directory.  If this is not a mistake, use the --allow-source-mismatch switch to avoid seeing this message"
msgstr ""

#: ../duplicity/manifest.py:218
#, python-format
msgid "Found manifest volume %s"
msgstr ""

#: ../duplicity/manifest.py:225
#, python-format
msgid "Found %s volumes in manifest"
msgstr ""

#: ../duplicity/manifest.py:243
#, python-format
msgid "Manifest file '%s' is corrupt: File count says %d, File list contains %d"
msgstr ""

#: ../duplicity/manifest.py:262
msgid "Manifests not equal because different volume numbers"
msgstr ""

#: ../duplicity/manifest.py:267
msgid "Manifests not equal because volume lists differ"
msgstr ""

#: ../duplicity/manifest.py:272
msgid "Manifests not equal because hosts or directories differ"
msgstr ""

#: ../duplicity/manifest.py:429
msgid "Warning, found extra Volume identifier"
msgstr ""

#: ../duplicity/manifest.py:455
msgid "Other is not VolumeInfo"
msgstr ""

#: ../duplicity/manifest.py:458
msgid "Volume numbers don't match"
msgstr ""

#: ../duplicity/manifest.py:461
msgid "start_indicies don't match"
msgstr ""

#: ../duplicity/manifest.py:464
msgid "end_index don't match"
msgstr ""

#: ../duplicity/manifest.py:471
msgid "Hashes don't match"
msgstr ""

#: ../duplicity/util.py:160 ../duplicity/dup_main.py:847
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr ""

#: ../duplicity/util.py:227
#, python-format
msgid "Releasing lockfile %s"
msgstr ""

#: ../duplicity/backends/pydrivebackend.py:181
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr ""

#: ../duplicity/backends/multibackend.py:96
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:105
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:160
#: ../duplicity/backends/multibackend.py:165
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:176
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:180
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: use store %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:194
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:207
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:248
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr ""

#: ../duplicity/backends/multibackend.py:261
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:268
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr ""

#: ../duplicity/backends/multibackend.py:275
#, python-format
msgid "MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:297
#, python-format
msgid "MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:307
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:310
#, python-format
msgid "Exception during list of %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:317
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:346
#: ../duplicity/backends/multibackend.py:375
#, python-format
msgid "MultiBackend: failed to delete %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/giobackend.py:109
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:85
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:106
msgid "Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:110
#, python-format
msgid "For certificate verification with python 2.7.8 or earlier a cacert database\n"
"file is needed in one of these locations: %s\n"
"Hints:\n"
"Consult the man page, chapter 'SSL Certificate Verification'.\n"
"Consider using the options --ssl-cacert-file, --ssl-no-check-certificate ."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:168
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:170
#, python-format
msgid "Using WebDAV directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:201
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:212
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:231
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:232
#: ../duplicity/backends/webdavbackend.py:255
#, python-format
msgid "WebDAV data length: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:235
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:241
#, python-format
msgid "WebDAV redirect to: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:243
msgid "WebDAV redirected 10 times. Giving up."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:248
msgid "WebDAV missing location header in redirect response."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:253
msgid "WebDAV retry request with authentification headers."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:254
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:258
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:275
msgid "python-kerberos needed to use kerberos                           authorization, falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:279
#, python-format
msgid "Kerberos authorization failed: %s.                          Falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:377
#, python-format
msgid "Creating missing directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:394
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:439
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:461
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:481
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr ""

#: ../duplicity/diffdir.py:115 ../duplicity/diffdir.py:418
#, python-format
msgid "Error %s getting delta for %s"
msgstr ""

#: ../duplicity/diffdir.py:130
#, python-format
msgid "Getting delta of %s and %s"
msgstr ""

#: ../duplicity/diffdir.py:181
#, python-format
msgid "A %s"
msgstr ""

#: ../duplicity/diffdir.py:188
#, python-format
msgid "M %s"
msgstr ""

#: ../duplicity/diffdir.py:210
#, python-format
msgid "Comparing %s and %s"
msgstr ""

#: ../duplicity/diffdir.py:218
#, python-format
msgid "D %s"
msgstr ""

#: ../duplicity/commandline.py:78
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in version 0.9.0.\n"
"Use of default filenames is strongly suggested."
msgstr ""

#: ../duplicity/commandline.py:85
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in a future release.\n"
"--include-filelist and --exclude-filelist now accept globbing characters and should be used instead."
msgstr ""

#: ../duplicity/commandline.py:95
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in a future release.\n"
"On many GNU/Linux systems, stdin is represented by /dev/stdin and\n"
"--include-filelist=/dev/stdin or --exclude-filelist=/dev/stdin could\n"
"be used as a substitute."
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:262 ../duplicity/commandline.py:272
#: ../duplicity/commandline.py:293 ../duplicity/commandline.py:389
#: ../duplicity/commandline.py:407 ../duplicity/commandline.py:418
#: ../duplicity/commandline.py:666 ../duplicity/commandline.py:714
#: ../duplicity/commandline.py:942
msgid "path"
msgstr ""

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:288 ../duplicity/commandline.py:295
#: ../duplicity/commandline.py:413 ../duplicity/commandline.py:647
#: ../duplicity/commandline.py:915
msgid "gpg-key-id"
msgstr ""

#. Used in usage help to represent a pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <pattern>
#: ../duplicity/commandline.py:303 ../duplicity/commandline.py:441
#: ../duplicity/commandline.py:948
msgid "pattern"
msgstr ""

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:309 ../duplicity/commandline.py:318
#: ../duplicity/commandline.py:325 ../duplicity/commandline.py:443
#: ../duplicity/commandline.py:450 ../duplicity/commandline.py:463
#: ../duplicity/commandline.py:911
msgid "filename"
msgstr ""

#. Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:332 ../duplicity/commandline.py:454
msgid "regular_expression"
msgstr ""

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:336 ../duplicity/commandline.py:401
#: ../duplicity/commandline.py:541 ../duplicity/commandline.py:997
msgid "time"
msgstr ""

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:409 ../duplicity/commandline.py:518
#: ../duplicity/commandline.py:544 ../duplicity/commandline.py:655
#: ../duplicity/commandline.py:930
msgid "options"
msgstr ""

#: ../duplicity/commandline.py:427
#, python-format
msgid "Running in 'ignore errors' mode due to %s; please re-consider if this was not intended"
msgstr ""

#. Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:439
msgid "imap_mailbox"
msgstr ""

#: ../duplicity/commandline.py:457
msgid "file_descriptor"
msgstr ""

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:472 ../duplicity/commandline.py:494
#: ../duplicity/commandline.py:515 ../duplicity/commandline.py:521
#: ../duplicity/commandline.py:527 ../duplicity/commandline.py:580
#: ../duplicity/commandline.py:585 ../duplicity/commandline.py:589
#: ../duplicity/commandline.py:612 ../duplicity/commandline.py:618
#: ../duplicity/commandline.py:622 ../duplicity/commandline.py:696
#: ../duplicity/commandline.py:709 ../duplicity/commandline.py:722
#: ../duplicity/commandline.py:925
msgid "number"
msgstr ""

#. Used in usage help (noun)
#: ../duplicity/commandline.py:475
msgid "backup name"
msgstr ""

#: ../duplicity/commandline.py:607
msgid "policy"
msgstr ""

#: ../duplicity/commandline.py:625
msgid "Hot|Cool|Archive"
msgstr ""

#. noun
#: ../duplicity/commandline.py:628 ../duplicity/commandline.py:631
#: ../duplicity/commandline.py:896
msgid "command"
msgstr ""

#: ../duplicity/commandline.py:634
msgid "pyrax|cloudfiles"
msgstr ""

#: ../duplicity/commandline.py:658
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#: ../duplicity/commandline.py:659
msgid "path to a folder with certificate authority files"
msgstr ""

#: ../duplicity/commandline.py:663
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr ""

#. Used in usage help. Example:
#. --timeout <seconds>
#. Used in usage help. Example:
#. --backend-retry-delay <seconds>
#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:671 ../duplicity/commandline.py:727
#: ../duplicity/commandline.py:965
msgid "seconds"
msgstr ""

#. abbreviation for "character" (noun)
#: ../duplicity/commandline.py:677 ../duplicity/commandline.py:893
msgid "char"
msgstr ""

#: ../duplicity/commandline.py:859
#, python-format
msgid "Using archive dir: %s"
msgstr ""

#: ../duplicity/commandline.py:860
#, python-format
msgid "Using backup name: %s"
msgstr ""

#: ../duplicity/commandline.py:867
#, python-format
msgid "Command line error: %s"
msgstr ""

#: ../duplicity/commandline.py:868
msgid "Enter 'duplicity --help' for help screen."
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:881
msgid "absolute_path"
msgstr ""

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:885
msgid "alias"
msgstr ""

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:890
msgid "bucket_name"
msgstr ""

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:901
msgid "container_name"
msgstr ""

#. noun
#: ../duplicity/commandline.py:904
msgid "count"
msgstr ""

#. Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:907
msgid "directory"
msgstr ""

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:920
msgid "module"
msgstr ""

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:934
msgid "other.host"
msgstr ""

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:938
msgid "password"
msgstr ""

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:952
msgid "port"
msgstr ""

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:957
msgid "prefix"
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:961
msgid "relative_path"
msgstr ""

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:970
msgid "some_dir"
msgstr ""

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:976
msgid "source_dir"
msgstr ""

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:981
msgid "source_url"
msgstr ""

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:987
msgid "target_dir"
msgstr ""

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:992
msgid "target_url"
msgstr ""

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:1002
msgid "user"
msgstr ""

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/commandline.py:1005
msgid "account_id"
msgstr ""

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/commandline.py:1009
msgid "application_key"
msgstr ""

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/commandline.py:1013 ../duplicity/dup_collections.py:517
msgid "remote"
msgstr ""

#. Header in usage help
#: ../duplicity/commandline.py:1032
msgid "Backends and their URL formats:"
msgstr ""

#. Header in usage help
#: ../duplicity/commandline.py:1070
msgid "Commands:"
msgstr ""

#: ../duplicity/commandline.py:1097
#, python-format
msgid "Specified archive directory '%s' does not exist, or is not a directory"
msgstr ""

#: ../duplicity/commandline.py:1106
#, python-format
msgid "Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""

#: ../duplicity/commandline.py:1166
#, python-format
msgid "Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr ""

#: ../duplicity/commandline.py:1171
#, python-format
msgid "Verify directory %s does not exist"
msgstr ""

#: ../duplicity/commandline.py:1177
#, python-format
msgid "Backup source directory %s does not exist."
msgstr ""

#: ../duplicity/commandline.py:1208
#, python-format
msgid "Command line warning: %s"
msgstr ""

#: ../duplicity/commandline.py:1208
msgid "Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr ""

#: ../duplicity/commandline.py:1244
#, python-format
msgid "GPG binary is %s, version %s"
msgstr ""

#: ../duplicity/commandline.py:1271
#, python-format
msgid "Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr ""

#: ../duplicity/commandline.py:1301
msgid "Main action: "
msgstr ""

#: ../duplicity/librsync.py:196
msgid "basis_file must be a (true) file or an object whose file attribute is the underlying true file object"
msgstr ""

#: ../duplicity/dup_time.py:63
#, python-format
msgid "Bad interval string \"%s\"\n\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""

#: ../duplicity/dup_time.py:69
#, python-format
msgid "Bad time string \"%s\"\n\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""

#: ../duplicity/dup_main.py:120
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr ""

#: ../duplicity/dup_main.py:127
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr ""

#: ../duplicity/dup_main.py:168
msgid "PASSPHRASE variable not set, asking user."
msgstr ""

#: ../duplicity/dup_main.py:183
msgid "GnuPG passphrase for signing key:"
msgstr ""

#: ../duplicity/dup_main.py:188
msgid "GnuPG passphrase for decryption:"
msgstr ""

#: ../duplicity/dup_main.py:193
msgid "Retype passphrase for signing key to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:195
msgid "Retype passphrase for decryption to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:198
msgid "First and second passphrases do not match!  Please try again."
msgstr ""

#: ../duplicity/dup_main.py:205
msgid "Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr ""

#: ../duplicity/dup_main.py:263
#, python-format
msgid "File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""

#: ../duplicity/dup_main.py:272
#, python-format
msgid "File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""

#: ../duplicity/dup_main.py:326
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d, retrying."
msgstr ""

#: ../duplicity/dup_main.py:331
#, python-format
msgid "File %s was corrupted during upload."
msgstr ""

#: ../duplicity/dup_main.py:371
msgid "Restarting backup, but current encryption settings do not match original settings"
msgstr ""

#: ../duplicity/dup_main.py:394
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr ""

#: ../duplicity/dup_main.py:397
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr ""

#: ../duplicity/dup_main.py:475
#, python-format
msgid "Processed volume %d"
msgstr ""

#: ../duplicity/dup_main.py:625
msgid "Fatal Error: Unable to start incremental backup.  Old signatures not found and incremental specified"
msgstr ""

#: ../duplicity/dup_main.py:629
msgid "No signatures found, switching to full backup."
msgstr ""

#: ../duplicity/dup_main.py:643
msgid "Backup Statistics"
msgstr ""

#: ../duplicity/dup_main.py:751
#, python-format
msgid "%s not found in archive - no files restored."
msgstr ""

#: ../duplicity/dup_main.py:755
msgid "No files found in archive - nothing restored."
msgstr ""

#: ../duplicity/dup_main.py:792
#, python-format
msgid "Processed volume %d of %d"
msgstr ""

#: ../duplicity/dup_main.py:837
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr ""

#: ../duplicity/dup_main.py:840
#, python-format
msgid "Calculated hash: %s"
msgstr ""

#: ../duplicity/dup_main.py:841
#, python-format
msgid "Manifest hash: %s"
msgstr ""

#: ../duplicity/dup_main.py:892
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr ""

#: ../duplicity/dup_main.py:924
#, python-format
msgid "Verify complete: %s, %s."
msgstr ""

#: ../duplicity/dup_main.py:925
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] ""

#: ../duplicity/dup_main.py:927
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] ""

#: ../duplicity/dup_main.py:946
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr ""

#: ../duplicity/dup_main.py:951
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] ""

#: ../duplicity/dup_main.py:962
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] ""

#: ../duplicity/dup_main.py:965
msgid "Run duplicity again with the --force option to actually delete."
msgstr ""

#: ../duplicity/dup_main.py:1008
msgid "There are backup set(s) at time(s):"
msgstr ""

#: ../duplicity/dup_main.py:1010
msgid "Which can't be deleted because newer sets depend on them."
msgstr ""

#: ../duplicity/dup_main.py:1014
msgid "Current active backup chain is older than specified time.  However, it will not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""

#: ../duplicity/dup_main.py:1027
msgid "No old backup sets found, nothing deleted."
msgstr ""

#: ../duplicity/dup_main.py:1030
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] ""

#: ../duplicity/dup_main.py:1042
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1044
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1047
#, python-format
msgid "Deleting complete signature chain %s"
msgstr ""

#: ../duplicity/dup_main.py:1049
#, python-format
msgid "Deleting complete backup chain %s"
msgstr ""

#: ../duplicity/dup_main.py:1055
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] ""

#: ../duplicity/dup_main.py:1059
msgid "Rerun command with --force option to actually delete."
msgstr ""

#: ../duplicity/dup_main.py:1082
msgid "No old backup sets found."
msgstr ""

#: ../duplicity/dup_main.py:1097
#, python-format
msgid "Signature %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1104 ../duplicity/dup_main.py:1143
#, python-format
msgid "Replicating %s."
msgstr ""

#: ../duplicity/dup_main.py:1131
#, python-format
msgid "Backupset %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1279
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr ""

#: ../duplicity/dup_main.py:1284
#, python-format
msgid "Unable to delete %s: %s"
msgstr ""

#: ../duplicity/dup_main.py:1318 ../duplicity/dup_temp.py:271
#, python-format
msgid "Failed to read %s: %s"
msgstr ""

#: ../duplicity/dup_main.py:1331
#, python-format
msgid "Copying %s to local cache."
msgstr ""

#: ../duplicity/dup_main.py:1379
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""

#: ../duplicity/dup_main.py:1384
msgid "Synchronizing remote metadata to local cache..."
msgstr ""

#: ../duplicity/dup_main.py:1397
msgid "Sync would copy the following from remote to local:"
msgstr ""

#: ../duplicity/dup_main.py:1400
msgid "Sync would remove the following spurious local files:"
msgstr ""

#: ../duplicity/dup_main.py:1444
msgid "Unable to get free space on temp."
msgstr ""

#: ../duplicity/dup_main.py:1452
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""

#: ../duplicity/dup_main.py:1455
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr ""

#: ../duplicity/dup_main.py:1463
msgid "Unable to get max open files."
msgstr ""

#: ../duplicity/dup_main.py:1467
#, python-format
msgid "Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""

#: ../duplicity/dup_main.py:1519
msgid "RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""

#: ../duplicity/dup_main.py:1525
#, python-format
msgid "RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""

#: ../duplicity/dup_main.py:1532
#, python-format
msgid "RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last partial\n"
"         backup then restart the backup from the beginning."
msgstr ""

#: ../duplicity/dup_main.py:1553
msgid "\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1576
#, python-format
msgid "Acquiring lockfile %s"
msgstr ""

#: ../duplicity/dup_main.py:1639
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1643
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1655
msgid "Last full backup date:"
msgstr ""

#: ../duplicity/dup_main.py:1657
msgid "Last full backup date: none"
msgstr ""

#: ../duplicity/dup_main.py:1660
msgid "Last full backup is too old, forcing full backup"
msgstr ""

#: ../duplicity/dup_main.py:1709
msgid "When using symmetric encryption, the signing passphrase must equal the encryption passphrase."
msgstr ""

#: ../duplicity/asyncscheduler.py:70
#, python-format
msgid "instantiating at concurrency %d"
msgstr ""

#: ../duplicity/asyncscheduler.py:97
msgid "inserting barrier"
msgstr ""

#: ../duplicity/asyncscheduler.py:146
msgid "running task synchronously (asynchronicity disabled)"
msgstr ""

#: ../duplicity/asyncscheduler.py:152
msgid "scheduling task for asynchronous execution"
msgstr ""

#: ../duplicity/asyncscheduler.py:181
msgid "task completed successfully"
msgstr ""

#: ../duplicity/asyncscheduler.py:192
msgid "a previously scheduled task has failed; propagating the result immediately"
msgstr ""

#: ../duplicity/asyncscheduler.py:215 ../duplicity/asyncscheduler.py:236
#, python-format
msgid "active workers = %d"
msgstr ""

#: ../duplicity/asyncscheduler.py:256
#, python-format
msgid "task execution done (success: %s)"
msgstr ""

#: ../duplicity/gpginterface.py:241
msgid "Threading not available -- zombie processes may appear"
msgstr ""

#: ../duplicity/gpginterface.py:710
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr ""

#: ../duplicity/robust.py:64
#, python-format
msgid "Error listing directory %s"
msgstr ""

#: ../duplicity/dup_collections.py:186 ../duplicity/dup_collections.py:200
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/dup_collections.py:225
msgid "Fatal Error: No manifests found for most recent backup"
msgstr ""

#: ../duplicity/dup_collections.py:234
msgid "Fatal Error: Remote manifest does not match local one.  Either the remote backup set or the local archive directory has been corrupted."
msgstr ""

#: ../duplicity/dup_collections.py:242
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr ""

#: ../duplicity/dup_collections.py:253
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:265
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr ""

#: ../duplicity/dup_collections.py:268
#, python-format
msgid "Processing remote manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:364
msgid "Preferring Backupset over previous one!"
msgstr ""

#: ../duplicity/dup_collections.py:367
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""

#: ../duplicity/dup_collections.py:372
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr ""

#: ../duplicity/dup_collections.py:442
msgid "Chain start time: "
msgstr ""

#: ../duplicity/dup_collections.py:443
msgid "Chain end time: "
msgstr ""

#: ../duplicity/dup_collections.py:444
#, python-format
msgid "Number of contained backup sets: %d"
msgstr ""

#: ../duplicity/dup_collections.py:446
#, python-format
msgid "Total number of contained volumes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:448 ../duplicity/dup_collections.py:1247
msgid "Type of backup set:"
msgstr ""

#: ../duplicity/dup_collections.py:448 ../duplicity/dup_collections.py:1247
msgid "Time:"
msgstr ""

#: ../duplicity/dup_collections.py:448
msgid "Num volumes:"
msgstr ""

#: ../duplicity/dup_collections.py:452 ../duplicity/dup_collections.py:1253
msgid "Full"
msgstr ""

#: ../duplicity/dup_collections.py:455 ../duplicity/dup_collections.py:1255
msgid "Incremental"
msgstr ""

#: ../duplicity/dup_collections.py:515
msgid "local"
msgstr ""

#: ../duplicity/dup_collections.py:672
msgid "Collection Status"
msgstr ""

#: ../duplicity/dup_collections.py:674
#, python-format
msgid "Connecting with backend: %s"
msgstr ""

#: ../duplicity/dup_collections.py:676
#, python-format
msgid "Archive dir: %s"
msgstr ""

#: ../duplicity/dup_collections.py:679
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] ""

#: ../duplicity/dup_collections.py:684
#, python-format
msgid "Secondary chain %d of %d:"
msgstr ""

#: ../duplicity/dup_collections.py:690
msgid "Found primary backup chain with matching signature chain:"
msgstr ""

#: ../duplicity/dup_collections.py:694
msgid "No backup chains with active signatures found"
msgstr ""

#: ../duplicity/dup_collections.py:697
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] ""

#: ../duplicity/dup_collections.py:701
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:706
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr ""

#: ../duplicity/dup_collections.py:709
msgid "No orphaned or incomplete backup sets found."
msgstr ""

#: ../duplicity/dup_collections.py:725
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] ""

#: ../duplicity/dup_collections.py:735
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] ""

#: ../duplicity/dup_collections.py:788
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr ""

#: ../duplicity/dup_collections.py:811
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] ""

#: ../duplicity/dup_collections.py:820
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] ""

#: ../duplicity/dup_collections.py:829
msgid "Warning, found signatures but no corresponding backup files"
msgstr ""

#: ../duplicity/dup_collections.py:833
msgid "Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""

#: ../duplicity/dup_collections.py:837
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] ""

#: ../duplicity/dup_collections.py:854
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr ""

#: ../duplicity/dup_collections.py:866
#, python-format
msgid "File %s is part of known set"
msgstr ""

#: ../duplicity/dup_collections.py:869
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr ""

#: ../duplicity/dup_collections.py:874
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr ""

#: ../duplicity/dup_collections.py:890
#, python-format
msgid "Found backup chain %s"
msgstr ""

#: ../duplicity/dup_collections.py:895
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr ""

#: ../duplicity/dup_collections.py:899
#, python-format
msgid "Found orphaned set %s"
msgstr ""

#: ../duplicity/dup_collections.py:1049
#, python-format
msgid "No signature chain for the requested time. Using oldest available chain, starting at time %s."
msgstr ""

#: ../duplicity/dup_collections.py:1245
#, python-format
msgid "File: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1246
#, python-format
msgid "Total number of backup: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1247 ../duplicity/dup_collections.py:1273
msgid "Type of file change:"
msgstr ""

#: ../duplicity/dup_collections.py:1271
#, python-format
msgid " Backup set time: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1272
#, python-format
msgid "Total number of changes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1273
msgid "File:"
msgstr ""

#: ../duplicity/patchdir.py:83 ../duplicity/patchdir.py:88
#, python-format
msgid "Patching %s"
msgstr ""

#: ../duplicity/patchdir.py:558
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:633
#, python-format
msgid "Writing %s of type %s"
msgstr ""

#: ../duplicity/selection.py:117
#, python-format
msgid "Skipping socket %s"
msgstr ""

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr ""

#: ../duplicity/selection.py:125 ../duplicity/selection.py:150
#: ../duplicity/selection.py:517
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr ""

#: ../duplicity/selection.py:165
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr ""

#: ../duplicity/selection.py:168 ../duplicity/selection.py:186
#: ../duplicity/selection.py:189
#, python-format
msgid "Selecting %s"
msgstr ""

#: ../duplicity/selection.py:245
#, python-format
msgid "The last file selection option is the filter option %s, which will have no\n"
"effect as there are no subsequent file selection options. Exiting because\n"
"this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:254
#, python-format
msgid "Only these filter mode options were specified:\n"
"    %s\n"
"Case sensitive globbing is the default behaviour and so this has no effect.\n"
"Exiting because this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:325
#, python-format
msgid "Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr ""

#: ../duplicity/selection.py:334
#, python-format
msgid "Fatal Error while processing expression\n"
"%s"
msgstr ""

#: ../duplicity/selection.py:343
#, python-format
msgid "Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:402
#, python-format
msgid "Reading %s filelist %s"
msgstr ""

#: ../duplicity/selection.py:443
#, python-format
msgid "Error compiling regular expression %s"
msgstr ""

#: ../duplicity/lazy.py:355
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr ""

#: ../duplicity/lazy.py:430
#, python-format
msgid "Error '%s' processing %s"
msgstr ""

#: ../duplicity/lazy.py:440
#, python-format
msgid "Skipping %s because of previous error"
msgstr ""

#: ../duplicity/path.py:115
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:245 ../duplicity/path.py:306
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr ""

#: ../duplicity/path.py:370
msgid "Difference found:"
msgstr ""

#: ../duplicity/path.py:379
#, python-format
msgid "New file %s"
msgstr ""

#: ../duplicity/path.py:382
#, python-format
msgid "File %s is missing"
msgstr ""

#: ../duplicity/path.py:385
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr ""

#: ../duplicity/path.py:391 ../duplicity/path.py:417
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr ""

#: ../duplicity/path.py:396
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr ""

#: ../duplicity/path.py:404
#, python-format
msgid "Data for file %s is different"
msgstr ""

#: ../duplicity/path.py:412
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr ""

#: ../duplicity/path.py:421
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr ""

#: ../duplicity/path.py:613
#, python-format
msgid "Making directory %s"
msgstr ""

#: ../duplicity/path.py:623
#, python-format
msgid "Deleting %s"
msgstr ""

#: ../duplicity/path.py:632
#, python-format
msgid "Touching %s"
msgstr ""

#: ../duplicity/path.py:639
#, python-format
msgid "Deleting tree %s"
msgstr ""

